source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PandaHTTP_Example', :exclusive => true do
  pod 'PandaHTTP', :path => '../'
end

target 'PandaHTTP_Tests', :exclusive => true do
  pod 'PandaHTTP', :path => '../'

  
end
